### ISSUE TITLE
Daily Tracking

### ISSUE THREAD

**Issue by JohnAkerman** [JohnAkerman/TabStats#14]
We have an initial start but it would be good to have multi-day tracking that can be separated out on a day, week or month basis. This can be used later for graphing.

- [ ] Track each day
- [ ] Most active day of week
- [ ] Least active day of week
- [x] Most active hour

These could be in the form of line or pie charts.

[Example charts](http://code.shutterstock.com/rickshaw/)

**Comment by JohnAkerman** [comment]
Just a thought regarding tracking, we can store tabId's which I believe can be reused over time. We could store an array with tabId's as the key and use it to store creation date and updated time. We can use this to store the URL as well, although if we store it this way we won't be able to keep track of URLs, so it would be physical tabs rather than websites.

We could store tab data using ``location.origin`` which would allow us to track the top level domain more efficiently as it won't matter what the full URL is.

**Comment by JohnAkerman** [comment]
We now have hits stored depending on the top level domain with a hit being a datetime string added to an array.

I have now added some custom functions to the import branch that can be used to pull out certain states.

**Comment by JohnAkerman** [comment]
I think for this to go live we will need the ability to remove yourself from website tracking - we could instead store the website as "Anonymous" which would then allow us to store hits as we currently do but it would all be categorised as one rather than individual domains.

I think this would open up the ability to save more _advanced options_ in another window.  I know this can be achieved using built-in options if we don't want to make a custom backend for it.
